fruit=("banana","orange","grapes","banana","mango","pineapple","apple","orange","grapes","banana","kiwi")
print("Fruits:-")
print(fruit)
i=input("Enter the fruit whose no. you have to find:-")
print("No. of fruits in the tuple:-"+str(fruit.count(i)))
j=input("Enter the fruit whose index you have to find:-")
print("Index of fruit:-"+str(fruit.index(j)))
